import type { Page } from "./types";

export const PAGES: Page[] = [
  {
    step: 1,
    title: "Your Machine",
    subtitle: "Tell us about the Mac you use so we can tailor your assessment.",
    questions: [
      {
        id: "name",
        label: "Your name",
        type: "text",
        required: true,
        placeholder: "e.g. Jane Smith",
      },
      {
        id: "email",
        label: "Email address",
        type: "email",
        required: true,
        placeholder: "e.g. jane@example.com",
      },
      {
        id: "popia_consent",
        label: "Consent",
        type: "consent",
        required: true,
        consentText:
          "I consent to ZA Support processing the information I provide in this assessment to prepare a personalised risk report and contact me by email about the outcome. Processing is carried out in accordance with the Protection of Personal Information Act (Act 4 of 2013). I may request that my data is updated or removed at any time by emailing mary@zasupport.com.",
      },
      {
        id: "machine_type",
        label: "What type of Mac do you use?",
        type: "single",
        required: true,
        options: [
          { label: "MacBook Air", value: "MacBook Air" },
          { label: "MacBook Pro", value: "MacBook Pro" },
          { label: "iMac", value: "iMac" },
          { label: "Mac mini", value: "Mac mini" },
          { label: "Mac Studio", value: "Mac Studio" },
          { label: "Mac Pro", value: "Mac Pro" },
        ],
      },
      {
        id: "mac_year",
        label: "What year is your Mac approximately?",
        type: "single",
        required: true,
        options: [
          { label: "2018 or earlier", value: "2018 or earlier" },
          { label: "2019–2021", value: "2019-2021" },
          { label: "2022–2024", value: "2022-2024" },
          { label: "2025+", value: "2025+" },
        ],
      },
      {
        id: "macos_version",
        label: "Which macOS are you running?",
        type: "single",
        required: true,
        options: [
          { label: "Monterey (12)", value: "Monterey" },
          { label: "Ventura (13)", value: "Ventura" },
          { label: "Sonoma (14)", value: "Sonoma" },
          { label: "Sequoia (15)", value: "Sequoia" },
          { label: "Not sure", value: "Not sure" },
        ],
      },
    ],
  },
  {
    step: 2,
    title: "Security Status",
    subtitle: "We assess your current security posture to identify immediate risks.",
    questions: [
      {
        id: "filevault_enabled",
        label: "Is FileVault disk encryption enabled?",
        type: "single",
        required: true,
        options: [
          { label: "Yes", value: "Yes", riskWeight: 0 },
          { label: "No", value: "No", riskWeight: 25 },
          { label: "Not sure", value: "Not sure", riskWeight: 15 },
        ],
      },
      {
        id: "backup_status",
        label: "Do you have an active backup?",
        type: "single",
        required: true,
        options: [
          { label: "Time Machine running", value: "Time Machine running", riskWeight: 0 },
          { label: "Cloud backup only", value: "Cloud backup only", riskWeight: 5 },
          { label: "External drive (manual)", value: "External drive (manual)", riskWeight: 10 },
          { label: "No backup", value: "No backup", riskWeight: 25 },
          { label: "Not sure", value: "Not sure", riskWeight: 15 },
        ],
      },
      {
        id: "last_backup",
        label: "When did your last backup complete?",
        type: "single",
        required: true,
        options: [
          { label: "Today", value: "Today", riskWeight: 0 },
          { label: "This week", value: "This week", riskWeight: 2 },
          { label: "This month", value: "This month", riskWeight: 5 },
          { label: "More than a month ago", value: "More than a month ago", riskWeight: 15 },
          { label: "Never", value: "Never", riskWeight: 20 },
          { label: "Not sure", value: "Not sure", riskWeight: 10 },
        ],
      },
      {
        id: "security_software",
        label: "Do you have antivirus or security software?",
        type: "single",
        required: true,
        options: [
          { label: "Yes (Malwarebytes / CrowdStrike)", value: "Yes", riskWeight: 0 },
          { label: "No", value: "No", riskWeight: 15 },
          { label: "Relying on macOS only", value: "macOS only", riskWeight: 5 },
          { label: "Not sure", value: "Not sure", riskWeight: 8 },
        ],
      },
    ],
  },
  {
    step: 3,
    title: "Your Data",
    subtitle: "Understanding what you store helps us assess your exposure and compliance risk.",
    questions: [
      {
        id: "data_types",
        label: "What data do you store on this Mac? Select all that apply.",
        type: "multi",
        required: false,
        options: [
          { label: "Online banking / financial apps", value: "banking", riskWeight: 3 },
          { label: "Tax documents (SARS)", value: "tax", riskWeight: 3 },
          { label: "Personal photos and videos", value: "photos", riskWeight: 3 },
          { label: "Work or client files", value: "work_files", riskWeight: 3 },
          { label: "Saved passwords (Keychain)", value: "passwords", riskWeight: 3 },
          { label: "Health or medical records", value: "medical", riskWeight: 3 },
          { label: "ID or passport copies", value: "id_docs", riskWeight: 3 },
          { label: "Personal email archive", value: "email", riskWeight: 3 },
        ],
      },
      {
        id: "public_wifi",
        label: "Do you use this Mac on public Wi-Fi?",
        type: "single",
        required: true,
        options: [
          { label: "Regularly", value: "Regularly", riskWeight: 10 },
          { label: "Occasionally", value: "Occasionally", riskWeight: 5 },
          { label: "Never", value: "Never", riskWeight: 0 },
        ],
      },
      {
        id: "sharing",
        label: "Do you share this Mac with anyone?",
        type: "single",
        required: true,
        options: [
          { label: "Yes — family members", value: "family", riskWeight: 5 },
          { label: "Yes — work colleagues", value: "colleagues", riskWeight: 8 },
          { label: "No", value: "No", riskWeight: 0 },
        ],
      },
    ],
  },
  {
    step: 4,
    title: "Monitoring Priorities",
    subtitle: "Tell us what matters most so we can customise your Health Check Scout coverage.",
    questions: [
      {
        id: "priority_areas",
        label: "Which of these monitoring areas concern you most? Select all that apply.",
        type: "multi",
        required: false,
        options: [
          { label: "Battery health and lifespan", value: "battery" },
          { label: "Backup verification", value: "backup" },
          { label: "Malware and security threats", value: "malware" },
          { label: "Privacy permissions (camera, microphone)", value: "privacy" },
          { label: "Performance and app behaviour", value: "performance" },
          { label: "Disk health and storage", value: "disk" },
          { label: "Network and firewall security", value: "network" },
          { label: "System and software updates", value: "updates" },
          { label: "Data encryption status", value: "encryption" },
          { label: "Hardware sensor monitoring (fans, temperature)", value: "sensors" },
        ],
      },
      {
        id: "it_management",
        label: "How do you currently manage IT issues?",
        type: "single",
        required: true,
        options: [
          { label: "I handle it myself", value: "self", riskWeight: 8 },
          { label: "IT support company", value: "IT company", riskWeight: 0 },
          { label: "ZA Support", value: "ZA Support", riskWeight: 0 },
          { label: "Family or friend", value: "family", riskWeight: 5 },
          { label: "No one", value: "No one", riskWeight: 15 },
        ],
      },
    ],
  },
  {
    step: 5,
    title: "IT History",
    subtitle: "Past issues and events help us understand your risk profile more accurately.",
    questions: [
      {
        id: "past_issues",
        label: "Have you experienced any of the following? Select all that apply.",
        type: "multi",
        required: false,
        options: [
          { label: "Slow performance", value: "slow", riskWeight: 4 },
          { label: "Unexpected shutdowns or crashes", value: "crashes", riskWeight: 4 },
          { label: "Data loss", value: "data_loss", riskWeight: 4 },
          { label: "Suspected malware or virus", value: "malware", riskWeight: 4 },
          { label: "Overheating", value: "overheating", riskWeight: 4 },
          { label: "Battery problems", value: "battery", riskWeight: 4 },
          { label: "Screen or display issues", value: "display", riskWeight: 4 },
          { label: "None of the above", value: "none", riskWeight: 0 },
        ],
      },
      {
        id: "security_warnings",
        label: "Have you ever received a security warning from macOS or a browser?",
        type: "single",
        required: true,
        options: [
          { label: "Yes — and I addressed it", value: "addressed", riskWeight: 0 },
          { label: "Yes — I ignored or dismissed it", value: "ignored", riskWeight: 15 },
          { label: "No", value: "No", riskWeight: 0 },
          { label: "Not sure", value: "Not sure", riskWeight: 5 },
        ],
      },
      {
        id: "repair_history",
        label: "Has this Mac been in for repair in the last 2 years?",
        type: "single",
        required: true,
        options: [
          { label: "Yes — through ZA Support", value: "ZA Support", riskWeight: 0 },
          { label: "Yes — through Apple", value: "Apple", riskWeight: 0 },
          { label: "Yes — third-party repairer", value: "third party", riskWeight: 5 },
          { label: "No", value: "No", riskWeight: 0 },
        ],
      },
    ],
  },
  {
    step: 6,
    title: "Compliance",
    subtitle: "Compliance and business use significantly affect your risk and obligations under POPIA.",
    questions: [
      {
        id: "business_use",
        label: "Do you use this Mac for any business purpose?",
        type: "single",
        required: true,
        options: [
          { label: "Yes — primary work machine", value: "primary", riskWeight: 8 },
          { label: "Yes — occasionally for work", value: "occasional", riskWeight: 4 },
          { label: "No — personal only", value: "personal", riskWeight: 0 },
        ],
      },
      {
        id: "client_data",
        label: "Do you handle client or patient data on this Mac?",
        type: "single",
        required: true,
        options: [
          { label: "Yes — regularly", value: "regularly", riskWeight: 15 },
          { label: "Yes — occasionally", value: "occasionally", riskWeight: 8 },
          { label: "No", value: "No", riskWeight: 0 },
        ],
      },
      {
        id: "popia_awareness",
        label: "Are you aware of POPIA data protection requirements?",
        type: "single",
        required: true,
        options: [
          { label: "Yes — fully compliant", value: "compliant", riskWeight: 0 },
          { label: "Somewhat aware", value: "somewhat", riskWeight: 5 },
          { label: "No — not aware", value: "not aware", riskWeight: 12 },
        ],
      },
      {
        id: "audit_required",
        label: "Could you be asked to demonstrate IT security safeguards to an insurer or auditor?",
        type: "single",
        required: true,
        options: [
          { label: "Yes — definitely", value: "yes", riskWeight: 8 },
          { label: "Possibly", value: "possibly", riskWeight: 4 },
          { label: "No", value: "No", riskWeight: 0 },
          { label: "Not sure", value: "Not sure", riskWeight: 3 },
        ],
      },
    ],
  },
];
